### ISSUE TITLE
bug: If teamcity goes down, status polling can go into a loop

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/status.keyman.com#137]
This log entry gets continually repeated and we never receive any further TC notifications once an error occurs:

```
2021-07-27T20:25:36.270558992Z Data change for teamcity is still underway; waiting 10000 milliseconds
```

Looks like we need to catch failures somewhere:

```
2021-07-26T15:54:52.104880146Z Error: connect ETIMEDOUT 209.12.63.129:443
2021-07-26T15:54:52.104918646Z     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
2021-07-26T15:54:52.104924646Z   errno: 'ETIMEDOUT',
2021-07-26T15:54:52.104928346Z   code: 'ETIMEDOUT',
2021-07-26T15:54:52.104931946Z   syscall: 'connect',
2021-07-26T15:54:52.104935346Z   address: '209.12.63.129',
2021-07-26T15:54:52.104938946Z   port: 443
2021-07-26T15:54:52.104942546Z }
2021-07-26T15:54:52.105061248Z Error: connect ETIMEDOUT 209.12.63.129:443
2021-07-26T15:54:52.105071648Z     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
2021-07-26T15:54:52.105075948Z   errno: 'ETIMEDOUT',
2021-07-26T15:54:52.105079548Z   code: 'ETIMEDOUT',
2021-07-26T15:54:52.105083248Z   syscall: 'connect',
2021-07-26T15:54:52.105086748Z   address: '209.12.63.129',
2021-07-26T15:54:52.105090348Z   port: 443
2021-07-26T15:54:52.105093848Z }
```

**Comment by mcdurdin** [comment]
Fixed, I believe, with #139
